import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: " λ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-black text-white",
          fontSans.variable
        )}
      >
        <nav className="mx-96 mt-5 flex justify-between">
          <h1 className="text-3xl border border-red-500 rounded-full px-5 text-center">
            λ
          </h1>
          <h1 className="text-2xl font-bold">
            Anime <span className="text-red-500"> LIST </span>
          </h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
